services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people
      MYSQL_TCP_PORT: 3308
    restart: always
    expose:
      - 3308
    ports:
      - 3308:3308
    networks:
      - spring-db

  # demo = aplicacao Spring Boot
  demo:
    image: gustavoszo/demo
    restart: always
    # Opção de build para a img
    build: ./demo
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/people?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=America/Sao_Paulo
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - spring-db

networks:
  spring-db:
    driver: bridge